Import for whyred
Signed-off-by: farizmaul <ricoayuba88@gmail.com>

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -3,7 +3,7 @@
 # osm0sis @ xda-developers
 
 OUTFD=/proc/self/fd/$2;
-export ZIPFILE="$3";
+ZIPFILE="$3";
 
 BOOTMODE=false;
 ps | grep zygote | grep -v grep >/dev/null && BOOTMODE=true;
@@ -29,7 +29,7 @@ ui_printfile() {
   done < $1;
 }
 show_progress() { echo "progress $1 $2" >> $OUTFD; }
-file_getprop() { $BB grep "^$2=" "$1" | $BB cut -d= -f2-; }
+file_getprop() { $BB grep "^$2=" "$1" | $BB tail -n1 | $BB cut -d= -f2-; }
 find_slot() {
   local slot=$(getprop ro.boot.slot_suffix 2>/dev/null);
   [ "$slot" ] || slot=$($BB grep -o 'androidboot.slot_suffix=.*$' /proc/cmdline | $BB cut -d\  -f1 | $BB cut -d= -f2);
@@ -52,25 +52,26 @@ mount_apex() {
   [ -d /system_root/system/apex ] || return 1;
   local apex dest loop minorx num var;
   setup_mountpoint /apex;
+  $BB mount -t tmpfs tmpfs /apex -o mode=755 && $BB touch /apex/apextmp;
   minorx=1;
   [ -e /dev/block/loop1 ] && minorx=$($BB ls -l /dev/block/loop1 | $BB awk '{ print $6 }');
   num=0;
   for apex in /system_root/system/apex/*; do
-    dest=/apex/$($BB basename $apex .apex);
-    case $dest in
-      *.current|*.release) dest=$(echo $dest | $BB rev | $BB cut -d. -f2- | $BB rev);;
-    esac;
+    dest=/apex/$($BB basename $apex | $BB sed -E -e 's;\.apex$|\.capex$;;' -e 's;\.current$|\.release$;;');
     $BB mkdir -p $dest;
     case $apex in
-      *.apex)
+      *.apex|*.capex)
+        $BB unzip -qo $apex original_apex -d /apex;
+        [ -f /apex/original_apex ] && apex=/apex/original_apex;
         $BB unzip -qo $apex apex_payload.img -d /apex;
+        $BB mv -f /apex/original_apex $dest.apex 2>/dev/null;
         $BB mv -f /apex/apex_payload.img $dest.img;
         $BB mount -t ext4 -o ro,noatime $dest.img $dest 2>/dev/null;
         if [ $? != 0 ]; then
           while [ $num -lt 64 ]; do
             loop=/dev/block/loop$num;
-            ($BB mknod $loop b 7 $((num * minorx));
-            $BB losetup $loop $dest.img) 2>/dev/null;
+            [ -e $loop ] || $BB mknod $loop b 7 $((num * minorx));
+            $BB losetup $loop $dest.img 2>/dev/null;
             num=$((num + 1));
             $BB losetup $loop | $BB grep -q $dest.img && break;
           done;
@@ -89,9 +90,9 @@ mount_apex() {
   $($BB grep -o 'export .* /.*' /system_root/init.environ.rc | $BB sed 's; /;=/;'); unset export;
 }
 umount_apex() {
-  [ -d /apex/com.android.runtime ] || return 1;
+  [ -d /apex ] || return 1;
   local dest loop var;
-  for var in $($BB grep -o 'export .* /.*' /system_root/init.environ.rc | $BB awk '{ print $2 }'); do
+  for var in $($BB grep -o 'export .* /.*' /system_root/init.environ.rc 2>/dev/null | $BB awk '{ print $2 }'); do
     if [ "$(eval echo \$OLD_$var)" ]; then
       eval $var=\$OLD_${var};
     else
@@ -100,12 +101,11 @@ umount_apex() {
     unset OLD_${var};
   done;
   for dest in $($BB find /apex -type d -mindepth 1 -maxdepth 1); do
-    if [ -f $dest.img ]; then
-      loop=$($BB mount | $BB grep $dest | $BB cut -d\  -f1);
-    fi;
-    ($BB umount -l $dest;
-    $BB losetup -d $loop) 2>/dev/null;
+    loop=$($BB mount | $BB grep $dest | $BB grep loop | $BB cut -d\  -f1);
+    $BB umount -l $dest;
+    [ "$loop" ] && $BB losetup -d $loop;
   done;
+  [ -f /apex/apextmp ] && $BB umount /apex;
   $BB rm -rf /apex 2>/dev/null;
 }
 mount_all() {
@@ -243,7 +243,7 @@ restore_env() {
   $BB umount -l /dev/random) 2>/dev/null;
 }
 debugging() {
-  case $(basename "$ZIPFILE" .zip) in
+  case $($BB basename "$ZIPFILE" .zip) in
     *-debugging)
       ui_print " " "Creating debugging archive in $DIR...";
       [ -f /tmp/recovery.log ] && local log=/tmp/recovery.log;
@@ -267,22 +267,21 @@ abort() {
 do_devicecheck() {
   [ "$(file_getprop anykernel.sh do.devicecheck)" == 1 ] || return 1;
   local device devicename match product testname vendordevice vendorproduct;
-  ui_print "Checking device...";
   device=$(getprop ro.product.device 2>/dev/null);
   product=$(getprop ro.build.product 2>/dev/null);
   vendordevice=$(getprop ro.product.vendor.device 2>/dev/null);
   vendorproduct=$(getprop ro.vendor.product.device 2>/dev/null);
-  for testname in $(file_getprop anykernel.sh 'device.name.*'); do
+  for testname in $($BB grep '^device.name.*=' anykernel.sh | $BB cut -d= -f2-); do
     for devicename in $device $product $vendordevice $vendorproduct; do
       if [ "$devicename" == "$testname" ]; then
-        ui_print "$testname" " ";
+        ui_print "Device: $testname" " ";
         match=1;
         break 2;
       fi;
     done;
   done;
   if [ ! "$match" ]; then
-    abort " " "Unsupported device. Aborting...";
+    abort " " "Aborted! Reason: Unsupported device.";
   fi;
 }
 int2ver() {
@@ -297,7 +296,6 @@ int2ver() {
 do_versioncheck() {
   [ "$(file_getprop anykernel.sh supported.versions)" ] || return 1;
   local android_ver hi_ver lo_ver parsed_ver supported supported_ver;
-  ui_print "Checking Android version...";
   supported_ver=$(file_getprop anykernel.sh supported.versions | $BB tr -d '[:space:]');
   android_ver=$(file_getprop /system/build.prop ro.build.version.release);
   parsed_ver=$(int2ver $android_ver);
@@ -316,15 +314,14 @@ do_versioncheck() {
     done;
   fi;
   if [ "$supported" ]; then
-    ui_print "$android_ver" " ";
+    ui_print "Android Version: $android_ver" " ";
   else
-    abort " " "Unsupported Android version. Aborting...";
+    abort " " "Aborted! Reason: Unsupported Android version.";
   fi;
 }
 do_levelcheck() {
   [ "$(file_getprop anykernel.sh supported.patchlevels)" ] || return 1;
   local android_lvl hi_lvl lo_lvl parsed_lvl supported_lvl;
-  ui_print "Checking Android security patch level...";
   supported_lvl=$(file_getprop anykernel.sh supported.patchlevels | $BB grep -oE '[0-9]{4}-[0-9]{2}|-');
   android_lvl=$(file_getprop /system/build.prop ro.build.version.security_patch);
   parsed_lvl=$(echo $android_lvl | $BB grep -oE '[0-9]{4}-[0-9]{2}');
@@ -339,13 +336,13 @@ do_levelcheck() {
     hi_lvl=9999-99;
   fi;
   if echo -e "$hi_lvl\n$lo_lvl\n$parsed_lvl" | $BB sort -g | $BB grep -n "$parsed_lvl" | $BB grep -q '^2:'; then
-    ui_print "$android_lvl" " ";
+    ui_print "Security Patch: $android_lvl" " ";
   else
-    abort " " "Unsupported Android security patch level. Aborting...";
+    abort " " "Aborted! Reason: Unsupported Android security patch level.";
   fi;
 }
 dump_moduleinfo() {
-cat <<EOF > $1;
+$BB cat <<EOF > $1;
 name=AK3 Helper Module
 version=$($BB awk '{ print $3 }' $AKHOME/vertmp) $($BB grep -oE '#.[0-9]' $AKHOME/vertmp)
 versionCode=1
@@ -354,7 +351,7 @@ description=$KERNEL_STRING
 EOF
 }
 dump_moduleremover() {
-cat <<'EOF' > $1;
+$BB cat <<'EOF' > $1;
 #!/system/bin/sh
 MODDIR=${0%/*};
 if [ "$(cat /proc/version)" != "$(cat $MODDIR/version)" ]; then
@@ -373,13 +370,13 @@ do_modules() {
       umask 022;
       moddir=/data/adb/modules/ak3-helper;
       $BB rm -rf $moddir;
-      mkdir -p system $moddir;
+      $BB mkdir -p system $moddir;
       ($BB mv -f product system;
       $BB mv -f vendor system) 2>/dev/null;
       $BB cp -rLf * $moddir;
       dump_moduleinfo $moddir/module.prop;
       dump_moduleremover $moddir/post-fs-data.sh;
-      cp -f $AKHOME/vertmp $moddir/version;
+      $BB cp -f $AKHOME/vertmp $moddir/version;
       umask $umask;
     else
       ui_print "Magisk installation not found. Skipped!";
@@ -399,7 +396,7 @@ do_modules() {
       ($BB mount -o rw,remount -t auto /vendor;
       $BB mount -o rw,remount -t auto /product) 2>/dev/null;
     fi;
-    for module in $(find . -name '*.ko'); do
+    for module in $($BB find . -name '*.ko'); do
       modtarget=$POSTINSTALL$(echo $module | $BB cut -c2-);
       if [ ! -e $modtarget ]; then
         case $module in
@@ -411,7 +408,7 @@ do_modules() {
       if is_mounted $modtarget; then
         $BB mount -o rw,remount -t auto $modtarget;
       fi;
-      mkdir -p $(dirname $modtarget);
+      $BB mkdir -p $($BB dirname $modtarget);
       $BB cp -rLf $module $modtarget;
       $BB chown 0:0 $modtarget;
       $BB chmod 644 $modtarget;
@@ -465,13 +462,19 @@ if [ -f banner ]; then
 fi;
 
 KERNEL_STRING="$(file_getprop anykernel.sh kernel.string)";
-ui_print "$KERNEL_STRING";
+DEV_STRING="$(file_getprop anykernel.sh dev.string)";
+ui_print " " "Kernel: $KERNEL_STRING";
+ui_print "Dev: $DEV_STRING" " ";
+
 if [ -f version ]; then
   ui_print " ";
   ui_printfile version;
   ui_print " ";
 fi;
-ui_print " " "AnyKernel3 by osm0sis @ xda-developers" " " " ";
+
+ui_print "Thx to osm0sis @ xda-developers for AnyKernel3" " ";
+$BB grep -oE 'AK_BASE.*' META-INF/com/google/android/updater-script >&2;
+ui_print " ";
 
 setup_env;
 
@@ -479,7 +482,6 @@ do_devicecheck;
 do_versioncheck;
 do_levelcheck;
 
-ui_print "Installing...";
 CORE=$($BB grep -oE 'ak.*core.sh' anykernel.sh);
 [ -f tools/$CORE ] || $BB ln -s $AKHOME/tools/ak*-core.sh $AKHOME/tools/$CORE;
 PATH="$AKHOME/bin:$PATH" home=$AKHOME $BB ash anykernel.sh $2;
@@ -488,12 +490,10 @@ if [ $? != 0 ]; then
 fi;
 
 do_modules;
-
 debugging;
 restore_env;
-
 if [ "$(file_getprop anykernel.sh do.cleanup)" == 1 ]; then
   cleanup;
 fi;
 
-ui_print " " " " "Done!";
+ui_print "Thanks for installing $KERNEL_STRING!" " ";
